### ISSUE TITLE
installed this tweak but get drone fw version low prompt

### ISSUE THREAD

**Issue by tangbingk** [fpv-wtf/wtfos-tweaks#1]
I installed this tweak-prevent-force-upgrade tweak. In fpv drone mode, I connected the goggles to my iphone. With the latest dji fly app and phone connected to the Intenet, I got the drone/goggles fw versions low prompt. Now I cant arm my drone. Is there any way to fix this？

**Comment by j005u** [comment]
Sorry for the awfully late response, but the tl;dr; is you need to downgrade the drone as it's the one refusing to arm because the goggles are too old.
